# Configuration file for the genetic grid optimizer

grid:
  rows: 3        # number of rows (n)
  cols: 3        # number of columns (m)

items:
  auto_planter:
    range: 3      # Chebyshev radius of effect
    cost: 3.5       # placement cost
  auto_fertilizer:
    range: 3
    cost: 1
  auto_sprinkler:
    range: 3  
    cost: 1
  auto_harvester:
    range: 3
    cost: 1.5

# Plant growth parameters
grow:
  time: 10            # ticks to fully grow at base speed
  fertilizer_bonus: 0.25  # additional growth speed when fertilized
  water_bonus: 0.25       # additional growth speed when watered

# Genetic algorithm parameters
ga:
  population_size: 5000   # number of layouts per generation
  mutation_rate: 0.2   # per-cell mutation probability
  crossover_rate: 0.7   # probability of taking gene from parent A in crossover
  top_k: 2500              # number of elites to carry to next generation

# Simulation parameters
simulation:
  evaluation_ticks: 100   # number of ticks per layout evaluation
