# Configuration file for the genetic grid optimizer

grid:
  rows: 8        # number of rows (n)
  cols: 8        # number of columns (m)

items:
  auto_planter:
    range: 5      # Chebyshev radius of effect
    cost: 3.5       # placement cost
  auto_fertilizer:
    range: 5
    cost: 1
  auto_sprinkler:
    range: 5
    cost: 1
  auto_harvester:
    range: 5
    cost: 1.5

# Plant growth parameters
grow:
  time: 4            # ticks to fully grow at base speed
  fertilizer_bonus: 0.25  # additional growth speed when fertilized
  water_bonus: 0.25       # additional growth speed when watered

# Genetic algorithm parameters
ga:
  population_size: 10000   # number of layouts per generation
  mutation_rate: 0.2   # per-cell mutation probability
  crossover_rate: 0.7   # probability of taking gene from parent A in crossover
  top_k: 5000              # number of elites to carry to next generation

# Simulation parameters
simulation:
  evaluation_ticks: 40   # number of ticks per layout evaluation
